name: Auto Facebook Comment

on:
  workflow_dispatch:  # 👈 Important for manual run

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run Bot
        run: node script.js
